# Generated by Django 4.2.30 on 2026-04-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('REGULAR', 'Regular'), ('SUPPLEMENTARY', 'Supplementary')], default='REGULAR', max_length=20)),
                ('total_marks', models.IntegerField(default=100)),
                ('passing_marks', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=50)),
                ('available_seats', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_roll_number', models.CharField(max_length=20)),
                ('end_roll_number', models.CharField(max_length=20)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_assignments', to='exams.exam')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_assignments', to='accounts.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=15)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='exams.slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('external_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('is_pass', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_results', to='accounts.faculty')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'exam', 'attempt_number')},
            },
        ),
    ]
